### ISSUE TITLE
iOS not pairing with tvOS Simulator

### ISSUE THREAD

**Issue by yoshyosh** [flufff42/RealmTV#2]
After compiling the app onto my iOS device, I open the tvOS app in the simulator. Then when I press enter to play the first talk, it plays on the tvOS simulator. However nothing happens on my iOS device.

I expected the transcript to show on my device and the ability to control the tvOS screen.

**Comment by seanlabastille** [comment]
Under the hood `AsyncNetwork` uses Bonjour to advertise and look up the server, which in this case is the tvOS app.

You can try running `dns-sd -B "_AsyncNetwork._tcp" "local."` in a terminal to see if the service is being advertised properly.

Your iOS device will need to be able to see this advertisement, ideally on the same subnet as the machine you are running the simulator on.

**Comment by seanlabastille** [comment]
I'm closing this for now as the communication layer has been rewritten to use Multipeer Connectivity.
